export const ADD_AUTH_TOKEN = "ADD_AUTH_TOKEN";
export const DELETE_AUTH_TOKEN = "DELETE_AUTH_TOKEN";

export const ADD_USER_PROFILE_INFO = "ADD_USER_PROFILE_INFO";

export const ADD_MENU_INFO = "ADD_MENU_INFO";
export const UPDATE_MENU_LOADING_STATE = "UPDATE_MENU_LOADING_STATE";

export const SHRINK_SIDEBAR = 'SHRINK_SIDEBAR';