import {
  faBath,
  faCalendarCheck,
  faClinicMedical,
  faDog,
  faHistory,
  faHospitalUser,
  faIdBadge,
  faPaw,
  faSyringe,
  faTablets,
} from "@fortawesome/free-solid-svg-icons";
import {
  URL_PET_ADMIN_CLINC,
  URL_PET_ADMIN_GROOM,
  URL_PET_ADMIN_LICENSE,
  URL_PET_ADMIN_MEDICINE,
  URL_PET_ADMIN_PET_TYPES,
  URL_PET_ADMIN_PETS,
  URL_PET_ADMIN_STAFF,
  URL_PET_ADMIN_VACCINE,
  URL_PET_STAFF_APPT,
  URL_PET_STAFF_APPT_HISTORY,
  URL_PET_USERS_ADOPT,
  URL_PET_USERS_APPT,
  URL_PET_USERS_LICENSE,
  URL_PET_USERS_PETS,
} from "../config/UrlRoute";

export const HOME_DATA = [
  {
    title: "Adopt Pets",
    desc: "Do you love pets. Don't wait to Adopt",
    icon: faPaw,
    showDefault: true,
    role: "CLIENT",
    url: URL_PET_USERS_ADOPT,
    text: "Adopt Pets",
  },
  {
    title: "My Pets",
    desc: "Manage all your pets from the single place",
    icon: faDog,
    showDefault: true,
    role: "CLIENT",
    url: URL_PET_USERS_PETS,
    text: "My Pets",
  },
  {
    title: "Pet License",
    desc: "Do apply for the license without going out",
    icon: faIdBadge,
    showDefault: true,
    role: "CLIENT",
    url: URL_PET_USERS_LICENSE,
    text: "License",
  },
  {
    title: "Pet Appointment",
    desc: "Book the veterinarian appointment for your pets",
    icon: faCalendarCheck,
    showDefault: true,
    role: "CLIENT",
    url: URL_PET_USERS_APPT,
    text: "Appointments",
  },
  {
    title: "Appointments",
    desc: "See all your visiting clinic appointments",
    icon: faCalendarCheck,
    showDefault: false,
    role: "STAFF",
    url: URL_PET_STAFF_APPT,
    text: "View Appointment",
  },
  {
    title: "Appointment History",
    desc: "See the glands of all your past appointments",
    icon: faHistory,
    showDefault: false,
    role: "STAFF",
    url: URL_PET_STAFF_APPT_HISTORY,
    text: "History",
  },
  {
    title: "Add Pet Types",
    desc: "Add different categories of pet such as Cat, Dog, etc",
    icon: faPaw,
    showDefault: false,
    role: "ADMIN",
    url: URL_PET_ADMIN_PET_TYPES,
    text: "Pet Types",
  },
  {
    title: "Add Unadopt Pets",
    desc: "Make an entry for the unadopted pets",
    icon: faDog,
    showDefault: false,
    role: "ADMIN",
    url: URL_PET_ADMIN_PETS,
    text: "Add Pets",
  },
  {
    title: "Add Clinic",
    desc: "Add the new clinic which are managed by Pawsomecare",
    icon: faClinicMedical,
    showDefault: false,
    role: "ADMIN",
    url: URL_PET_ADMIN_CLINC,
    text: "Clinic",
  },
  {
    title: "Add Staff",
    desc: "Add the new staff for the clinic as either Veterinarian/Grooming",
    icon: faHospitalUser,
    showDefault: false,
    role: "ADMIN",
    url: URL_PET_ADMIN_STAFF,
    text: "Staff",
  },
  {
    title: "Add Medicine",
    desc: "Prepare the medicine entry for the Pawsomecare managed clinics",
    icon: faTablets,
    showDefault: false,
    role: "ADMIN",
    url: URL_PET_ADMIN_MEDICINE,
    text: "Medicine",
  },
  {
    title: "Add Vaccine",
    desc: "Add the entry for the vaccine",
    icon: faSyringe,
    showDefault: false,
    role: "ADMIN",
    url: URL_PET_ADMIN_VACCINE,
    text: "Vaccine",
  },
  {
    title: "Groom Services",
    desc: "Add the vast grooming services for the pets",
    icon: faBath,
    showDefault: false,
    role: "ADMIN",
    url: URL_PET_ADMIN_GROOM,
    text: "Grooming",
  },
  {
    title: "Approve the License",
    desc: "Approve and give the pet license for the pets owned by clients",
    icon: faIdBadge,
    showDefault: false,
    role: "ADMIN",
    url: URL_PET_ADMIN_LICENSE,
    text: "License",
  },
];
